
import * as constants from "../constants/index";

export const SET_SCREEN = "SET_SCREEN";

export const LOGOUT = "LOGOUT";
export const AUTHENTICATED = "AUTHENTICATED";
export const FETCH_PROVIDERS = "FETCH_PROVIDERS";

export const CALL_API_FSA = "CALL_API_FSA";

export const REMOVE_AUTH_TOKEN = "REMOVE_AUTH_TOKEN";
export const SET_AUTH_PROFILE = "SET_AUTH_PROFILE";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED";

export const WAITING_TO_LOAD_CURRENT_USER = "WAITING_TO_LOAD_CURRENT_USER";
export const LOADING_CURRENT_USER_PROCESS_VALIDATED = "LOADING_CURRENT_USER_PROCESS_VALIDATED";

export const REQUEST = "REQUEST";
export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESHING_TOKEN = "REFRESHING_TOKEN";
export const REFRESHING_TOKEN_SUCCESS = "REFRESHING_TOKEN_SUCCESS";
export const REFRESHING_TOKEN_FAILURE = "REFRESHING_TOKEN_FAILURE";

export const AUTH0_LOGIN = "AUTH0_LOGIN";
export const AUTH0_LOGOUT = "AUTH0_LOGOUT";

export const LOGGING_IN = "LOGGING_IN";

export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const UPDATE_EDITS = "UPDATE_EDITS";
export const CLEAR_EDITS = "CLEAR_EDITS";
export const CLEAR_POSTS = "CLEAR_POSTS";
